project:
  type: website
  output-dir: docs

website:
  title: "张思情 | 环境工程学者"
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: education.qmd
        text: 教育背景
      - href: honors.qmd 
        text: 荣誉奖项
      - href: contact.qmd
        text: 联系方式

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    code-link: true
